version: '3.8'

services:
  bioclinical-bert:
    build: .
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - HF_HOME=/app/cache
    volumes:
      - ./models_cache:/app/cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 3G
    restart: unless-stopped

networks:
  default:
    name: medical_mcp_network
    external: true